// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/dfs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHeartbeat) Reset() {
	*x = NodeHeartbeat{}
	mi := &file_internal_proto_dfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeartbeat) ProtoMessage() {}

func (x *NodeHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_dfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeartbeat.ProtoReflect.Descriptor instead.
func (*NodeHeartbeat) Descriptor() ([]byte, []int) {
	return file_internal_proto_dfs_proto_rawDescGZIP(), []int{0}
}

func (x *NodeHeartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_internal_proto_dfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_dfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_dfs_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_internal_proto_dfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_dfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_dfs_proto_rawDescGZIP(), []int{2}
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_internal_proto_dfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_dfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_internal_proto_dfs_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_internal_proto_dfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_dfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_dfs_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type AllocateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkRequest) Reset() {
	*x = AllocateChunkRequest{}
	mi := &file_internal_proto_dfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkRequest) ProtoMessage() {}

func (x *AllocateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_dfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkRequest.ProtoReflect.Descriptor instead.
func (*AllocateChunkRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_dfs_proto_rawDescGZIP(), []int{5}
}

func (x *AllocateChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *AllocateChunkRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AllocateChunkRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Chunks        []*ChunkMetadata       `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_internal_proto_dfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_dfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_internal_proto_dfs_proto_rawDescGZIP(), []int{6}
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetChunks() []*ChunkMetadata {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type ChunkMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Nodes         []string               `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkMetadata) Reset() {
	*x = ChunkMetadata{}
	mi := &file_internal_proto_dfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMetadata) ProtoMessage() {}

func (x *ChunkMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_dfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMetadata.ProtoReflect.Descriptor instead.
func (*ChunkMetadata) Descriptor() ([]byte, []int) {
	return file_internal_proto_dfs_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkMetadata) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkMetadata) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_proto_dfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_dfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_proto_dfs_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_internal_proto_dfs_proto protoreflect.FileDescriptor

const file_internal_proto_dfs_proto_rawDesc = "" +
	"\n" +
	"\x18internal/proto/dfs.proto\x12\x03dfs\"(\n" +
	"\rNodeHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\")\n" +
	"\vFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"6\n" +
	"\x05Chunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\")\n" +
	"\fChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"n\n" +
	"\x14AllocateChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\"V\n" +
	"\fFileMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12*\n" +
	"\x06chunks\x18\x02 \x03(\v2\x12.dfs.ChunkMetadataR\x06chunks\"@\n" +
	"\rChunkMetadata\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x14\n" +
	"\x05nodes\x18\x02 \x03(\tR\x05nodes\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x88\x02\n" +
	"\x0fMetadataService\x12'\n" +
	"\fRegisterNode\x12\r.dfs.NodeInfo\x1a\b.dfs.Ack\x121\n" +
	"\n" +
	"CreateFile\x12\x10.dfs.FileRequest\x1a\x11.dfs.FileMetadata\x12.\n" +
	"\aGetFile\x12\x10.dfs.FileRequest\x1a\x11.dfs.FileMetadata\x12>\n" +
	"\rAllocateChunk\x12\x19.dfs.AllocateChunkRequest\x1a\x12.dfs.ChunkMetadata\x12)\n" +
	"\tHeartbeat\x12\x12.dfs.NodeHeartbeat\x1a\b.dfs.Ack2`\n" +
	"\x0fDataNodeService\x12\"\n" +
	"\n" +
	"StoreChunk\x12\n" +
	".dfs.Chunk\x1a\b.dfs.Ack\x12)\n" +
	"\bGetChunk\x12\x11.dfs.ChunkRequest\x1a\n" +
	".dfs.ChunkB\x1dZ\x1bDFS_GO/internal/proto;protob\x06proto3"

var (
	file_internal_proto_dfs_proto_rawDescOnce sync.Once
	file_internal_proto_dfs_proto_rawDescData []byte
)

func file_internal_proto_dfs_proto_rawDescGZIP() []byte {
	file_internal_proto_dfs_proto_rawDescOnce.Do(func() {
		file_internal_proto_dfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_dfs_proto_rawDesc), len(file_internal_proto_dfs_proto_rawDesc)))
	})
	return file_internal_proto_dfs_proto_rawDescData
}

var file_internal_proto_dfs_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_proto_dfs_proto_goTypes = []any{
	(*NodeHeartbeat)(nil),        // 0: dfs.NodeHeartbeat
	(*NodeInfo)(nil),             // 1: dfs.NodeInfo
	(*FileRequest)(nil),          // 2: dfs.FileRequest
	(*Chunk)(nil),                // 3: dfs.Chunk
	(*ChunkRequest)(nil),         // 4: dfs.ChunkRequest
	(*AllocateChunkRequest)(nil), // 5: dfs.AllocateChunkRequest
	(*FileMetadata)(nil),         // 6: dfs.FileMetadata
	(*ChunkMetadata)(nil),        // 7: dfs.ChunkMetadata
	(*Ack)(nil),                  // 8: dfs.Ack
}
var file_internal_proto_dfs_proto_depIdxs = []int32{
	7, // 0: dfs.FileMetadata.chunks:type_name -> dfs.ChunkMetadata
	1, // 1: dfs.MetadataService.RegisterNode:input_type -> dfs.NodeInfo
	2, // 2: dfs.MetadataService.CreateFile:input_type -> dfs.FileRequest
	2, // 3: dfs.MetadataService.GetFile:input_type -> dfs.FileRequest
	5, // 4: dfs.MetadataService.AllocateChunk:input_type -> dfs.AllocateChunkRequest
	0, // 5: dfs.MetadataService.Heartbeat:input_type -> dfs.NodeHeartbeat
	3, // 6: dfs.DataNodeService.StoreChunk:input_type -> dfs.Chunk
	4, // 7: dfs.DataNodeService.GetChunk:input_type -> dfs.ChunkRequest
	8, // 8: dfs.MetadataService.RegisterNode:output_type -> dfs.Ack
	6, // 9: dfs.MetadataService.CreateFile:output_type -> dfs.FileMetadata
	6, // 10: dfs.MetadataService.GetFile:output_type -> dfs.FileMetadata
	7, // 11: dfs.MetadataService.AllocateChunk:output_type -> dfs.ChunkMetadata
	8, // 12: dfs.MetadataService.Heartbeat:output_type -> dfs.Ack
	8, // 13: dfs.DataNodeService.StoreChunk:output_type -> dfs.Ack
	3, // 14: dfs.DataNodeService.GetChunk:output_type -> dfs.Chunk
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_dfs_proto_init() }
func file_internal_proto_dfs_proto_init() {
	if File_internal_proto_dfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_dfs_proto_rawDesc), len(file_internal_proto_dfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_proto_dfs_proto_goTypes,
		DependencyIndexes: file_internal_proto_dfs_proto_depIdxs,
		MessageInfos:      file_internal_proto_dfs_proto_msgTypes,
	}.Build()
	File_internal_proto_dfs_proto = out.File
	file_internal_proto_dfs_proto_goTypes = nil
	file_internal_proto_dfs_proto_depIdxs = nil
}
